version: '3.8'

name: scout

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scout
      POSTGRES_USER: scout
      POSTGRES_PASSWORD: super_secret_password
    ports:
      - "9356:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scout -d scout"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  goose-migrations:
    build:
      context: .
      dockerfile: ./Dockerfile.goose
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
      
  scout:
    env_file:
      - ./.env.docker
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      goose-migrations:
        condition: service_completed_successfully
    ports:
      - "5601:5601"
    restart: unless-stopped

volumes:
  postgres_data: 